### ISSUE TITLE
Textual search to filter runs in `manage`

### ISSUE THREAD

**Issue by VGPReys** [i-VRESSE/haddock3-webapp#100]
**Is your feature request related to a problem? Please describe.**
In the `Manage` table where all the run are displayed, when so many runs are available on the webserver, it becomes difficult to find one specific one.

**Describe the solution you'd like**
A simple filtering solution based on text and applied on the run names could help finding what the user is searching for

**Comment by sverhoeven** [comment]
As workaround could be to increase the page size and use CTRL-f to find the job you want.

How many runs do you think users would have?

That can be done with https://ui.shadcn.com/docs/components/data-table#filtering .
The whole job list is fetched from bartender webservice. If the becomse to big then we might have to move the filter logic from the haddock3-webapp to bartender.
