### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Peter9192** [i-VRESSE/haddock3-webapp#22]
Currently any error returns an empty page with a big red traceback block. It would be nice if we could make this a bit more graceful.

![image](https://user-images.githubusercontent.com/17080502/222131316-905ff09c-9ea7-44d2-9fa8-fc830a29a472.png)

**Comment by Peter9192** [comment]
see http://remix.run/docs/en/1.13.0/route/error-boundary and http://remix.run/docs/en/1.13.0/tutorials/jokes#unexpected-errors

**Comment by sverhoeven** [comment]
Bartender errors are now forwarded see https://github.com/i-VRESSE/bartended-haddock3/commit/6c4b1a0ee959ab68780041bbe9fd426952542270

**Comment by sverhoeven** [comment]
https://github.com/i-VRESSE/bartended-haddock3/pull/47#pullrequestreview-1578308524 also mentions error reporting improvements.

**Comment by sverhoeven** [comment]
PR #71 form errors are handled.
