### ISSUE TITLE
Renable egi authentication

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-webapp#64]
For egi auth the remix-keycloak package is used, however latest version (2.0.4), while being remix v2 compatible is not typescript valid.

In 4a0a22dafc533192d5c8c767bcf8271bd6285e3d it was removed.

Once 2.0.5 of remix-keycloak is released we can renable egi login.

**Comment by dmijatovic** [comment]
The [remix-keycloak](https://github.com/marsmars0x01/remix-keycloak) is still on 2.0.4 version as of June 2024
