### ISSUE TITLE
The node buttons render incorrectly after navigation away and back

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-webapp#78]
**Describe the bug**
Rendering of nodes in build page should render the same each time.

**To Reproduce**

1. Goto http://localhost:3000/builder
2. Hover over topoaa node, it should look like :

![localhost_3000_builder](https://github.com/i-VRESSE/haddock3-webapp/assets/1713488/c65f1392-893e-4ae8-b928-c088e7584f7a)

3. Navigate to About page and back to build page. The topoaa node on hover now looks like

![localhost_3000_](https://github.com/i-VRESSE/haddock3-webapp/assets/1713488/b07137ff-f8b0-434f-aa63-b83a13c53c08)

**Workaround**
Refreshing the page. The topoaa node on hover now looks like same as first time.

**Expected behavior**
The topoaa node on hover the second time looks the same as the first time.

**Comment by sverhoeven** [comment]
We could add extra css classes to https://github.com/i-VRESSE/workflow-builder/blob/main/packages/core/src/CatalogNode.tsx to make it easier to overwrite them in https://github.com/i-VRESSE/haddock3-webapp/blob/main/app/builder/Form.css

**Comment by dmijatovic** [comment]
After researching about the issue I come to conclusion that combining  CSS-in-JS, standard css and tailwind css should be avoided. Different approached are not aware of each other and the order CSS injection is important. In this specific case the injection of CSS is not "stable". Initially Form.css is injected before emotion styles and during page change the order is different and the original styles are overwritten.

In addition, there seem to be some challenges when CSS-in-JS is used with ErrorBoundaries in remix. See this [issue](https://github.com/remix-run/remix/issues/1136). There are fixes for emotion and remix but in our case the dependency library "@i-vresse/wb-core" uses emotion so it is not guaranteed that remix fixes will work in this case.

We decided to remove emotion from web-core library and use different css approach.
